//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rocket.DAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rocket.DAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string MAXACCOUNTLEVELLENGHT {
            get {
                return ResourceManager.GetString("MAXACCOUNTLEVELLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string MAXACCOUNTSTATUSLENGHT {
            get {
                return ResourceManager.GetString("MAXACCOUNTSTATUSLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string MAXBUILDINBLOCKGLENGHT {
            get {
                return ResourceManager.GetString("MAXBUILDINBLOCKGLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string MAXBUILDINGLENGHT {
            get {
                return ResourceManager.GetString("MAXBUILDINGLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string MAXCITYLENGHT {
            get {
                return ResourceManager.GetString("MAXCITYLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string MAXEMAILADDRESSLENGHT {
            get {
                return ResourceManager.GetString("MAXEMAILADDRESSLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        internal static string MAXFIRSTNAMELENGHT {
            get {
                return ResourceManager.GetString("MAXFIRSTNAMELENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string MAXFLATGLENGHT {
            get {
                return ResourceManager.GetString("MAXFLATGLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string MAXGENDERLENGHT {
            get {
                return ResourceManager.GetString("MAXGENDERLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string MAXHOWTOCALLLENGHT {
            get {
                return ResourceManager.GetString("MAXHOWTOCALLLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string MAXLANGUAGELENGHT {
            get {
                return ResourceManager.GetString("MAXLANGUAGELENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        internal static string MAXLASTNAMELENGHT {
            get {
                return ResourceManager.GetString("MAXLASTNAMELENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string MAXLCOUNTRYLENGHT {
            get {
                return ResourceManager.GetString("MAXLCOUNTRYLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string MAXLOGINLENGHT {
            get {
                return ResourceManager.GetString("MAXLOGINLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        internal static string MAXPASSWORDLENGHT {
            get {
                return ResourceManager.GetString("MAXPASSWORDLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string MAXPHONENUMBERLENGHT {
            get {
                return ResourceManager.GetString("MAXPHONENUMBERLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string MAXZIPCODELENGHT {
            get {
                return ResourceManager.GetString("MAXZIPCODELENGHT", resourceCulture);
            }
        }
    }
}
