//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rocket.Parser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rocket.Parser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albumview.aspx?ID=.
        /// </summary>
        internal static string AlbumInfoInternalPrefixId {
            get {
                return ResourceManager.GetString("AlbumInfoInternalPrefixId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #aspnetForm &gt; table &gt; tbody &gt; tr:nth-child(1) &gt; th &gt; div.
        /// </summary>
        internal static string AlbumInfoReleaseDateSelector {
            get {
                return ResourceManager.GetString("AlbumInfoReleaseDateSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #conGenres.
        /// </summary>
        internal static string AlbumInfoReleaseGenreSelector {
            get {
                return ResourceManager.GetString("AlbumInfoReleaseGenreSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #aspnetForm &gt; table &gt; tbody &gt; tr:nth-child(1) &gt; th &gt; a.
        /// </summary>
        internal static string AlbumInfoReleaseImageUrlSelector {
            get {
                return ResourceManager.GetString("AlbumInfoReleaseImageUrlSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ctl00_CPH_conAlbums_conAlbums &gt; tbody &gt; tr:nth-child({0}) &gt; td:nth-child({1}) &gt; a.
        /// </summary>
        internal static string AlbumInfoReleaseLinkSelector {
            get {
                return ResourceManager.GetString("AlbumInfoReleaseLinkSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #dvContent &gt; h1.
        /// </summary>
        internal static string AlbumInfoReleaseNameSelector {
            get {
                return ResourceManager.GetString("AlbumInfoReleaseNameSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #conTracks.
        /// </summary>
        internal static string AlbumInfoReleaseTrackListSelector {
            get {
                return ResourceManager.GetString("AlbumInfoReleaseTrackListSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Info.
        /// </summary>
        internal static string AlbumInfoSettings {
            get {
                return ResourceManager.GetString("AlbumInfoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lostfilm.
        /// </summary>
        internal static string LostfilmSettings {
            get {
                return ResourceManager.GetString("LostfilmSettings", resourceCulture);
            }
        }
    }
}
