//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rocket.BL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rocket.BL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This email is already registered in the system&quot;.
        /// </summary>
        internal static string EmailDuplicate {
            get {
                return ResourceManager.GetString("EmailDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cannot find valid dat using this parameters&quot;.
        /// </summary>
        internal static string EmptyModel {
            get {
                return ResourceManager.GetString("EmptyModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Episode {
            get {
                return ResourceManager.GetString("Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This Genre is already added&quot;.
        /// </summary>
        internal static string GenreDuplicate {
            get {
                return ResourceManager.GetString("GenreDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Genre with this name was not found&quot;.
        /// </summary>
        internal static string GenreWrongName {
            get {
                return ResourceManager.GetString("GenreWrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;посетитель&quot;.
        /// </summary>
        internal static string GuestAlias {
            get {
                return ResourceManager.GetString("GuestAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;User with that Id was not found&quot;.
        /// </summary>
        internal static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Rocket TEAM&quot;.
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;No Reply&quot;.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cannot delete email. This email is undefined in system&quot;.
        /// </summary>
        internal static string UndefinedEmail {
            get {
                return ResourceManager.GetString("UndefinedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string USERACCOUNTLOGINISEMPTY {
            get {
                return ResourceManager.GetString("USERACCOUNTLOGINISEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string USERACCOUNTLOGINMINLENGTH {
            get {
                return ResourceManager.GetString("USERACCOUNTLOGINMINLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string USERACCOUNTPASSWORDISEMPTY {
            get {
                return ResourceManager.GetString("USERACCOUNTPASSWORDISEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string USERACCOUNTPASSWORDLENGHT {
            get {
                return ResourceManager.GetString("USERACCOUNTPASSWORDLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; символов&quot;.
        /// </summary>
        internal static string USERACCOUNTPASSWORDLOGINPARTOFSTRINGFORCOMPOSITION {
            get {
                return ResourceManager.GetString("USERACCOUNTPASSWORDLOGINPARTOFSTRINGFORCOMPOSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string USERACCOUNTPASSWORDMINLENGHT {
            get {
                return ResourceManager.GetString("USERACCOUNTPASSWORDMINLENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -2.
        /// </summary>
        internal static string USEREXISTS {
            get {
                return ResourceManager.GetString("USEREXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string USERISNOTVALID {
            get {
                return ResourceManager.GetString("USERISNOTVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string USERPERSONFIRSTNAMEISEMPTY {
            get {
                return ResourceManager.GetString("USERPERSONFIRSTNAMEISEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string USERPERSONSECONDNAMEISEMPTY {
            get {
                return ResourceManager.GetString("USERPERSONSECONDNAMEISEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;FirstName or LastName cannot be empty&quot;.
        /// </summary>
        internal static string UserWrongFirstOrLastName {
            get {
                return ResourceManager.GetString("UserWrongFirstOrLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;User hasn&apos;t have this genre&quot;.
        /// </summary>
        internal static string UserWrongGenre {
            get {
                return ResourceManager.GetString("UserWrongGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The password differs from the password confirmation or does not meet the security requirements&quot;.
        /// </summary>
        internal static string UserWrongPassword {
            get {
                return ResourceManager.GetString("UserWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Email format is wrong&quot;.
        /// </summary>
        internal static string WrongEmailFormat {
            get {
                return ResourceManager.GetString("WrongEmailFormat", resourceCulture);
            }
        }
    }
}
